### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by snailfu** [Dragonrun1/edid-creator#1]
Hi:

I'm seeking so long for an opensource tool which can create customized EDID blob, google leads me here. From the repository name it seems this is what I searched. But I'm not a php guy, I have tried to "build" it and "run" it, but I failed to really "run" this program yet.
From my previous experience of Python or C/C++ under Linux, and through search some basic php knowledge, I have tried downloaded the composer tool and run "_php composer.phar install_" under the project directory. Then I run "_php bootstrap.php_", but nothing happened. I searched the source code in the lib directory, I only can find the class and function definition, I can't figure out where to call them at all. It seems there must be deep knowledge gap I can't only get from google. So, I posted this question here to seek help for how to use it, may you help me? Thanks very much.

**Comment by Dragonrun1** [comment]
Think of it more like a library or template of classes from c++ that you need to get an instance of what you care to change. So for example if you wanted to set the DisplayGamma on a empty edid:

``` php
<?php
// gamma_test.php
// Find Compose class autoloader.
require_once __DIR__ . '/bootstrip.php';
// Get new empty instance of Edid class.
$edid = new Edid();
// Optionally load existing edid file.
// $edid->setEdidFromBinaryFile('testEdid.bin');
//Get new instance of what you want to change.
$gamma = new DisplayGamma($edid);
// Set the new value.
$gamma->setDisplayGamma('0X01');
$edid->writeEdidToBinaryFile('testEdid.bin');
```

That's a very simple example of how to use some of it but hopefully enough to get you over the hump. BTW this is assuming you are running it from the commandline with something like
`php -f  "gamma_test.php"`
You can use it also in a web page but you'd have to add all the other stuff to display a web form and process it etc of course ;) like any other web app would need. Let me know if you have any other questions.

**Comment by snailfu** [comment]
Thank you very much. I have successfully run your example, now I close the issue.
